DiyetisyeniSec.Web/Models/ErrorViewModel.cs
using System;

namespace DiyetisyeniSec.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DiyetisyeniSec.Web/Controllers/HomeController.cs
using DiyetisyeniSec.Data;
using DiyetisyeniSec.Domain.Nutritionist;
using DiyetisyeniSec.Domain.SharedConstants;
using DiyetisyeniSec.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DiyetisyeniSec.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DiyetisyenDbContext _context; //startup
        public HomeController(ILogger<HomeController> logger,DiyetisyenDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            //veri tabanına yeni kayıt ekledik
            /*
            Nutritionist newNutritionist = new Nutritionist
            {
                Name = "Haydar Tuzun",
                CompanyName = "Tuzun Estetik",
                UniversityName = "Akdeniz Universitesi",
                City = "Antalya",
                Gender = Genders.Male,
            };
            newNutritionist.SetExperience(3);

            _context.Nutritionists.Add(newNutritionist);
            _context.SaveChanges();
            */
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DiyetisyeniSec.Web/Controllers/NutritionistController.cs
using DiyetisyeniSec.Data;
using DiyetisyeniSec.Domain.Nutritionist;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DiyetisyeniSec.Web.Controllers
{
    public class NutritionistController : Controller
    {
        private readonly DiyetisyenDbContext _context;
        public NutritionistController(DiyetisyenDbContext context)
        {
            _context=context;
        }
        public IActionResult Index()
        {
            var diyetisyenler=_context.Nutritionists.ToList();
            return View(diyetisyenler);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken] //Güvenlik için gerekli istek sahteciliğini önler
        public IActionResult Create(Nutritionist nutritionist)
        {
            if(nutritionist.Experience<4 && nutritionist.Experience>2 && nutritionist.UniversityName != "Akdeniz Universitesi")
            {
                ModelState.AddModelError("experience", "Eğer Akdeniz Üniversitesi Mezunu Değilseniz En Az 4 Yıl Tecübeniz Olmak Zorunda."); 
                //küçük modal ismini yazıp yaprsak altta olur hata mesajı
            }

            if (ModelState.IsValid)
            {
                _context.Nutritionists.Add(nutritionist);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nutritionist);
        }

        public IActionResult Edit(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }
            var diyetisyen= _context.Nutritionists.FirstOrDefault(x => x.Id == id);
            if (diyetisyen==null)
            {
                return NotFound();
            }
            return View(diyetisyen);
            /*
           _context.Nutritionists.Find(id);
           _context.Nutritionists.FirstOrDefault(x => x.Id == id);
           _context.Nutritionists.SingleOrDefault(x => x.Id == id);
           */
        }
        [HttpPost]
        [ValidateAntiForgeryToken] //Güvenlik için gerekli istek sahteciliğini önler
        public IActionResult Edit(Nutritionist nutritionist)
        {
            if (nutritionist.Experience < 4 && nutritionist.Experience > 2 && nutritionist.UniversityName != "Akdeniz Universitesi")
            {
                ModelState.AddModelError("experience", "Eğer Akdeniz Üniversitesi Mezunu Değilseniz En Az 4 Yıl Tecübeniz Olmak Zorunda.");
                //küçük modal ismini yazıp yaprsak altta olur hata mesajı
            }

            if (ModelState.IsValid)
            {
                _context.Nutritionists.Update(nutritionist);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nutritionist);
        }

        public IActionResult Delete(int? id)
        {
            var diyetisyen= _context.Nutritionists.FirstOrDefault(x => x.Id==id);
            if (diyetisyen==null)
            {
                return NotFound();
            }
            
            return View(diyetisyen);
        }
        [HttpPost,ActionName("Delete")] //ActionName bir attribute tags örneğidir.
        public IActionResult DeletePost(int? id)
        {
            var diyetisyen = _context.Nutritionists.FirstOrDefault(x => x.Id == id);
            if (diyetisyen == null)
            {
                return NotFound();
            }
            _context.Nutritionists.Remove(diyetisyen);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DiyetisyeniSec.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DiyetisyeniSec.Web/Views/Nutritionist/Create.cshtml
@model DiyetisyeniSec.Domain.Nutritionist.Nutritionist
<form method="post"> 
    <h1>
        Diyetisyeni Oluştur
    </h1>
    <!--Tüm hataları özet olarak yukarda da görmemizi sağlar-->
    <div asp-validation-summary="All"> 

    </div>

    <div class="girisAlani">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="girisAlani">
        <label asp-for="City"></label>
        <input asp-for="City" />
        <span asp-validation-for="City"></span>
    </div>

    <div class="girisAlani">
        <label asp-for="UniversityName"></label>
        <input asp-for="UniversityName" />
        <span asp-validation-for="UniversityName"></span>
    </div>

    <div class="girisAlani">
        <label asp-for="Experience"></label>
        <input asp-for="Experience" />
        <span asp-validation-for="Experience"></span>
    </div>

    <div class="girisAlani">
        <label asp-for="WebsiteURL"></label>
        <input asp-for="WebsiteURL" />
        <span asp-validation-for="WebsiteURL"></span>
    </div>

    <button class="kaydetmeButonu" type="submit">Kaydet</button>
    <button class="kaydetmeButonu" type="reset">Reset</button>
    <a asp-controller="Nutritionist" asp-action="Index">Listeye Geri Dön</a>

</form>
@*
    Hatalar sunucuya gitmez bu kod sayesinde Anlık olarak gerçekleşir kontroller
*@
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

DiyetisyeniSec.Web/Views/Nutritionist/Index.cshtml
@model List<DiyetisyeniSec.Domain.Nutritionist.Nutritionist>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Diyetisyenler</h1>
<table>
    <thead>
        <tr>
            <th>Diyetisyeni Adı</th>
            <th>Şehri</th>
            <th>Tecrübe</th>
            <th>Universite</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var nutritionist in Model)
        {
         <tr>
             <td>@nutritionist.Name</td>
             <td>@nutritionist.City</td>
             <td>@nutritionist.Experience</td>
             <td>@nutritionist.UniversityName</td>
             <td><a asp-controller="Nutritionist" asp-action="Edit" asp-route-id="@nutritionist.Id">Düzenle</a></td>
             <td><a asp-controller="Nutritionist" asp-action="Delete" asp-route-id="@nutritionist.Id">Sil</a></td>
         </tr>   
        }
    </tbody>
</table>

DiyetisyeniSec.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiyetisyeniSec.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diyetisyeni Seç</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik Sözleşmesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nutritionist" asp-action="Index">Diyetisyenler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DiyetisyeniSec.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>